name: Jobs

on: [push]

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly-2022-08-05

jobs:
  basic-test:
    runs-on: ubuntu-latest
    container:
        image: livingshade/os-env:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.rust_toolchain }}
          components: rust-src, llvm-tools-preview
          target: riscv64gc-unknown-none-elf
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
      - name: Run rCore tests
        run: |
          git config --global --add safe.directory /__w/rCore-Tutorial-Code-2023S/rCore-Tutorial-Code-2023S
          git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2023S.git ci-user
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2023S.git ci-user/user
          ID=`git rev-parse --abbrev-ref HEAD | grep -oP 'ch\K[0-9]'`
          cd ci-user && make test CHAPTER=$ID
          cd ..
      # - name: Run uCore tests
      #   run: |
      #     rm -rf ci-user
      #     git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2023S.git ci-user
      #     git clone https://github.com/LearningOS/uCore-Tutorial-Code-2023S.git ci-user/ucore
      #     git clone https://github.com/LearningOS/uCore-Tutorial-Test-2023S.git ci-user/ucore/user
      #     cd ci-user && make utest CHAPTER=$ID
      #     cd ..
  gitlab-mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: Gallium70/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.tsinghua.edu.cn/os-lab/public/rcore-tutorial-code-2023s"
      env:
        GITLAB_HOSTNAME: "git.tsinghua.edu.cn"
        GITLAB_PROJECT_ID: "20776"
        GITLAB_PROJECT_NAME: "rcore-tutorial-code-2023s"
        GITLAB_PROJECT_TOKEN: ${{secrets.GITLAB_PROJECT_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}